global:
route:
  group_by: ['alertname']
  group_wait: 10s
  receiver: 'slack'
  group_interval: 15s
  # repeat_interval: 45s

receivers:
- name: 'slack'
  slack_configs:
  - channel: "#devops"
    send_resolved: true
    api_url: 'https://hooks.slack.com/services/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'
